<div align="center">
<span style="color: red; font-size: 28px; font-weight: bold; text-shadow: 2px 2px 4px #888888;">
PIVOT Table in Pandas
</span>
</div>

In [3]:
import pandas as pd
df = pd.read_csv('./Database/Superstore-Sales.csv',encoding= 'latin1')
pivot = df.pivot_table(
            index = 'Region',
            columns = 'Ship Mode',
            values = 'Profit',
            aggfunc = 'sum')

pivot.sort_values(by=['Delivery Truck','Express Air','Regular Air'], ascending=False)

Ship Mode              Delivery Truck  Express Air  Regular Air
Region
Prarie                       88285.67     27239.36    205635.09
West                         57042.23     51027.18    188939.20
Atlantic                     54205.85     22819.22    161935.59
Ontario                      44243.58     24467.18    278157.78
Quebec                       20118.48     14676.29    105631.88
Yukon                         5643.33      6519.67     61686.21
Nunavut                       1482.94      -418.72      1776.89
Northwest Territories        -1377.21      1100.13    100930.16

<div align="center"> <span style="color: green; font-size: 18px; font-weight: bold; text-shadow: 1px 1px 2px #888888;"> üìò Explanation </span> </div>
1Ô∏è‚É£ <span style=" font-weight:bold" >index = 'Region' </span>
Sets 'Region' as the row labels of the resulting table.

Each unique value in the 'Region' column will become a separate row.

2Ô∏è‚É£ <span style=" font-weight:bold" >columns = 'Ship Mode' </span>
Sets 'Ship Mode' as the column headers of the pivot table.

Each unique value in the 'Ship Mode' column becomes a separate column.

3Ô∏è‚É£ <span style=" font-weight:bold" >values = 'Profit' </span>
Specifies that only the 'Profit' values will be included in the table.

These values will be summarized based on the chosen aggregation function.

4Ô∏è‚É£ <span style=" font-weight:bold" >aggfunc= 'sum'  </span>
Aggregates (sums up) the 'Profit' for each combination of 'Region' and 'Ship Mode'.

The resulting table shows the total profit for each ship mode within each region.